name: Lint/Test/Build
# Будет отрабатывать на push и pull request в main ветку
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  # Название job-ы
  Github-Actions-Job:
    # На какой ОС будут запускаться проверки
    runs-on: ubuntu-latest
    # Какая версия node.js будет использоваться
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Устанавливаем node.js на машину, которая запускает проверки
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Запускаем собственные скрипты
      - name: install modules
        run: npm install
      - name: project production build
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting styles
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
